### ISSUE TITLE
PHPUnit 7 support

### ISSUE THREAD

**Issue by ezzatron** [eloquent/phony-phpunit#1]
Releases ~ Feb 2.

**Comment by enumag** [comment]
Can I help with something to solve this?

**Comment by ezzatron** [comment]
The bulk of work here is already done over at [eloquent/phony#php71-minimum](https://github.com/eloquent/phony/tree/php71-minimum). Since PHPUnit 7 no longer supports PHP 7.0, I'm working on a new major version of Phony's core that does the same.

PHP 7.1 lets me take advantage of nullable and void types, so it will improve some interfaces, and allow me to throw out a bunch of conditional code for supporting PHP 7.0.

Here's what's left to do before I can roll out this feature:

1. Documentation updates, including any API and usage example changes.
2. Making a branch of `phony-phpunit` that uses `phony@php71-minimum`, updating the APIs to match upstream changes, updating CI configs, etc. etc.
3. Addressing any problems found by integrating the 2 repos in step 2.
4. Ideally, trying out the changes on some real-world test suites.
5. Releasing - change logs, tagging, waiting for builds, rinse, repeat.

Sorry it's taking a while, I've just been especially busy with real-world work, moving house etc. I will try to push this out over the next week or so. In the mean time, I opened a PR for the core changes so that they're open for discussion:  eloquent/phony#235

**Comment by ezzatron** [comment]
FYI, there's now a [preview branch](https://github.com/eloquent/phony-phpunit/tree/phpunit-7) for this if you need it.

**Comment by ezzatron** [comment]
@enumag This is in master now, and I have a `4.0.x-dev` branch alias set up, so you should be able to try it out with an `"eloquent/phony-phpunit": "^4"` constraint.

At least, I think so. I haven't used branch aliases much 😅

**Comment by enumag** [comment]
@ezzatron I just tried. it works just fine, good job!

**Comment by ezzatron** [comment]
Released in [4.0.0](https://github.com/eloquent/phony-phpunit/releases/4.0.0).
